<div class="Text_Header">Tkinter Widgets and actions supported for record/replay</div>
<div class="Text_Normal">The following lists the Tkinter widget types and the associated actions on them which 
PyUseCase 3.2 is currently capable of recording and replaying. Any type derived from the listed
types is also supported. (Note that tkMessageBox, while not directly supported by PyUseCase, can be handled
fairly painlessly by using "collect_traffic_py_module" in TextTest)
</div>
<div class="Text_Normal"><table border=1 cellpadding=1 cellspacing=1>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/button.html>Tkinter.Button</a></td><td><div class="Table_Text_Normal">clicked</div></td></tr>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/entry.html>Tkinter.Entry</a></td><td><div class="Table_Text_Normal">edited text</div></td></tr>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/label.html>Tkinter.Label</a></td><td><div class="Table_Text_Normal">left-clicked , middle-clicked , right-clicked</div></td></tr>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/menu.html>Tkinter.Menu</a></td><td><div class="Table_Text_Normal">select item</div></td></tr>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/tk.html>Tkinter.Tk</a></td><td><div class="Table_Text_Normal">closed</div></td></tr>
<tr><td><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/toplevel.html>Tkinter.Toplevel</a></td><td><div class="Table_Text_Normal">closed</div></td></tr>
</table></div>
<div class="Text_Header">Tkinter Widgets supported for automatic logging</div>
<div class="Text_Normal">
The following lists the Tkinter widget types whose status and changes PyUseCase 3.2 is 
currently capable of monitoring and logging. Any type derived from the listed types 
is also supported but will only have features of the listed type described.
</div>
<div class="Text_Normal">
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/button.html>Tkinter.Button</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/entry.html>Tkinter.Entry</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/frame.html>Tkinter.Frame</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/label.html>Tkinter.Label</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/menu.html>Tkinter.Menu</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/scrollbar.html>Tkinter.Scrollbar</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/text.html>Tkinter.Text</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/tk.html>Tkinter.Tk</a>
<li><a class="Text_Link" href=http://infohost.nmt.edu/tcc/help/pubs/tkinter/toplevel.html>Tkinter.Toplevel</a>
</div><div class="Text_Normal"><i>(Note that a textual version of this page can be auto-generated by running "pyusecase -s -i tkinter")</i></div>
