<div class="Text_Header">wxPython Widgets and actions supported for record/replay</div>
<div class="Text_Normal">The following lists the wxPython widget types and the associated actions on them which 
StoryText 3.10 is currently capable of recording and replaying. Any type derived from the listed
types is also supported.
</div>
<div class="Text_Normal"><table border=1 cellpadding=1 cellspacing=1>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Button-class.html>wx.Button</a></td><td><div class="Table_Text_Normal">Press</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.CheckBox-class.html>wx.CheckBox</a></td><td><div class="Table_Text_Normal">Check , CheckThirdState , Uncheck</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Choice-class.html>wx.Choice</a></td><td><div class="Table_Text_Normal">Choose</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.DirDialog-class.html>wx.DirDialog</a></td><td><div class="Table_Text_Normal">SelectDir</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.DirSelectorWidget-class.html>wx.DirSelectorWidget</a></td><td><div class="Table_Text_Normal">DirSelectorReply</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.FileDialog-class.html>wx.FileDialog</a></td><td><div class="Table_Text_Normal">SelectFile</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.FileSelectorWidget-class.html>wx.FileSelectorWidget</a></td><td><div class="Table_Text_Normal">FileSelectorReply</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Frame-class.html>wx.Frame</a></td><td><div class="Table_Text_Normal">Close , Menu</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.GetColourFromUserWidget-class.html>wx.GetColourFromUserWidget</a></td><td><div class="Table_Text_Normal">GetColourFromUserReply</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.GetFontFromUserWidget-class.html>wx.GetFontFromUserWidget</a></td><td><div class="Table_Text_Normal">GetFontFromUserReply</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.ListCtrl-class.html>wx.ListCtrl</a></td><td><div class="Table_Text_Normal">ListCtrlSelect</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.MessageBoxWidget-class.html>wx.MessageBoxWidget</a></td><td><div class="Table_Text_Normal">MessageBoxReply</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.TextCtrl-class.html>wx.TextCtrl</a></td><td><div class="Table_Text_Normal">TextEnter</div></td></tr>
<tr><td><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Window-class.html>wx.Window</a></td><td><div class="Table_Text_Normal">ContextMenu</div></td></tr>
</table></div>
<div class="Text_Header">wxPython Widgets supported for automatic logging</div>
<div class="Text_Normal">
The following lists the wxPython widget types whose status and changes StoryText 3.10 is 
currently capable of monitoring and logging. Any type derived from the listed types 
is also supported but will only have features of the listed type described.
</div>
<div class="Text_Normal">
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Button-class.html>wx.Button</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.CheckBox-class.html>wx.CheckBox</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Choice-class.html>wx.Choice</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Dialog-class.html>wx.Dialog</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Frame-class.html>wx.Frame</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.ListCtrl-class.html>wx.ListCtrl</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.Menu-class.html>wx.Menu</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.MenuBar-class.html>wx.MenuBar</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.MenuItem-class.html>wx.MenuItem</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.StaticText-class.html>wx.StaticText</a>
<li><a class="Text_Link" href=http://www.wxpython.org/docs/api/wx.TextCtrl-class.html>wx.TextCtrl</a>
</div><div class="Text_Normal"><i>(Note that a textual version of this page can be auto-generated by running "storytext -s -i wx")</i></div>
